version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: always
    stdin_open: true  # Keep the container open
    tty: true         # Enable a terminal for debugging
    networks:
      - occn-opensearch-net
    environment:
      - NODE_ENV=development # Set the environment to development

networks:
  occn-opensearch-net: